In [1]:
import numpy as np
import pandas as pd

In [2]:
d_counts = pd.read_csv("counts.tsv", sep="\t").rename(columns={"gene_id":"ensembl_id"}) # counts data, with ensembl_ids
d_zbgem = pd.read_csv("~/Documents/mlardelli/data/id_tables.csv")
d_mlardelli = pd.read_csv("~/Documents/mlardelli/data/mlardelli_ids.csv")
print(d_counts.shape, d_mlardelli.shape, d_zbgem.shape)

(25030, 33) (251, 4) (1636, 3)

In [4]:
# Load DE genes
d0 = pd.read_csv("/Users/don/Documents/mlardelli/data/de_genes.csv")
d0 = d0.loc[d0["ncbi_id"]!="undef"].rename(columns={"Ensembl ID":"ensembl_id"})
dz = pd.merge(d_counts, d0[["ensembl_id", "ncbi_id"]], on="ensembl_id")

print(d0.shape)

(203, 12)

In [8]:
d_counts

,ensembl_id,wt_6_0_1,wt_6_0_2,wt_6_0_3,wt_6_0_4,wt_6_1_2,wt_6_1_3,wt_6_1_4,wt_6_1_1,q96_6_0_1,...,wt_24_1_3,wt_24_1_4,q96_24_0_1,q96_24_0_2,q96_24_0_3,q96_24_0_4,q96_24_1_1,q96_24_1_2,q96_24_1_3,q96_24_1_4
0,ENSDARG00000000001,196.906989,336.300104,262.922831,220.824940,249.864000,463.472244,214.269727,214.616632,159.645503,...,255.374173,222.879143,276.154547,218.883128,235.38580,188.894282,144.754118,259.835067,199.837379,189.144806
1,ENSDARG00000000002,131.093011,217.699896,170.077169,167.175060,141.136000,273.527756,303.730273,149.383368,194.354497,...,245.625827,312.120857,319.845453,330.116872,424.61420,327.105718,402.245882,293.164933,356.162621,343.855194
2,ENSDARG00000000018,592.000000,1065.000000,752.000000,829.000000,795.000000,1241.000000,913.000000,828.000000,621.000000,...,767.000000,823.000000,886.000000,717.000000,775.00000,728.000000,667.000000,863.000000,777.000000,709.000000
3,ENSDARG00000000019,3204.000000,5108.000000,3561.000000,3872.000000,3405.000000,5793.000000,4741.000000,3694.000000,3164.000000,...,3809.000000,4375.000000,4864.000000,3647.000000,4772.00000,4603.000000,3720.000000,4032.000000,4082.000000,3378.000000
4,ENSDARG00000000068,217.000000,441.000000,302.000000,285.000000,326.000000,535.000000,342.000000,297.000000,243.000000,...,429.000000,295.000000,397.000000,389.000000,360.00000,351.000000,367.000000,396.000000,281.000000,287.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25025,ENSDARG00000117185,4.000000,1.000000,1.000000,0.000000,1.000000,2.000000,4.000000,1.000000,1.000000,...,0.000000,0.000000,1.000000,0.076979,0.00000,1.000000,1.000000,0.000000,0.000000,0.000000
25026,ENSDARG00000117189,0.000000,0.000000,0.000000,4.809816,0.000000,1.836903,1.249176,0.000000,0.000000,...,3.069579,0.000000,2.250326,3.509441,0.00000,0.000000,0.000000,0.000000,3.672975,0.000000
25027,ENSDARG00000117193,51.000000,121.000000,77.000000,69.000000,53.000000,118.000000,55.000000,65.000000,75.000000,...,57.000000,68.000000,54.482203,53.276799,62.00000,66.000000,40.000000,36.000000,57.000000,48.609581
25028,ENSDARG00000117200,59.363468,121.558816,57.643565,121.410744,81.342312,193.904807,76.725571,65.423152,113.324619,...,184.410235,413.921073,289.114519,281.075924,377.57164,253.467377,314.238698,132.866764,369.087230,157.771238
25029,ENSDARG00000117204,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,...,1.000000,0.000000,1.000000,3.000000,0.00000,1.000000,3.000000,1.000000,0.000000,1.000000

In [ ]:
cols = list(dz)
cols.insert(0, cols.pop(cols.index('ncbi_id')))
dz = dz[cols]
dz = dz.drop("ensembl_id", axis=1)

In [ ]:
dz.columns

In [ ]:
dz.to_csv("counts_filtered_for_expr.tsv", sep="\t", index=False)

In [ ]:
for ncbi_id in list(set(d2["ncbi_id"])):
    if ncbi_id not in list(set(d1["ncbi_id"])):
        print(ncbi_id)

In [ ]:
df = pd.read_csv("/Users/don/Documents/mlardelli/efluxing/eflux2-supp/journal.pone.0157101.s003/test_expr.txt", sep="\t")

In [ ]:
print(dz.shape)

In [ ]:
my_str = "%s"

for cnm in list(dz.columns[1:]):
    my_str += "%f"
print(my_str)